config = {
    "host": "192.168.3.100",
    "port": 8501,
    "folder_path": "C:/Users/Administrator/Desktop/DATA-X291",
    "ready_register": 1000,
    "change_file_register": 500,
    "machines": {
        "cover_assembly": {
            "trigger": 21001,
            "title": "カバー組込自動機 AS49001VAA\n(Cover assembly automatic machine)",
            "file_name": "Cover assembly automatic machine.csv",
            "fields": [
                {"header": "DMC Cover", "start": 21020, "words": 16, "type": "string"},
                {"header": "QR code on the circuit board", "start": 21050, "words": 16, "type": "string"},
                {"header": "DATE", "start": 21012, "words": 2, "type": "number"},
                {"header": "TIME", "start": 21014, "words": 2, "type": "number"},
            ],
        },
        "laser_welding": {
            "trigger": 22001,
            "title": "レーザー溶着　 WE06001VAA \n(Laser welding automatic machine)",
            "file_name": "Laser welding automatic machine.csv",
            "fields": [
                {"header": "DMC Cover", "start": 22020, "words": 16, "type": "string"},
                {"header": "DATE", "start": 22012, "words": 2, "type": "number"},
                {"header": "TIME", "start": 22014, "words": 2, "type": "number"},
                {"header": "Processing equipment serial number", "start": 22070, "words": 16, "type": "string"},
                {"header": "Set the maximum value GT2 (mm)", "start": 22100, "words": 2, "type": "number"},
                {"header": "Set the minimum value GT2 (mm)", "start": 22102, "words": 2, "type": "number"},
                {"header": "Measured value GT2-1 (mm)", "start": 22104, "words": 2, "type": "number"},
                {"header": "Measured value GT2-2 (mm)", "start": 22106, "words": 2, "type": "number"},
                {"header": "Result", "start": 22110, "words": 1, "type": "number"},
                {"header": "Pressure(N)", "start": 22112, "words": 2, "type": "number"},
                {"header": "Power (W)", "start": 22114, "words": 2, "type": "number"},
                {"header": "Number of repetitions (times)", "start": 22116, "words": 2, "type": "number"},
                {"header": "Scanning speed\n(mm/s)", "start": 22118, "words": 2, "type": "number"},
                {"header": "Hold pressure time (ms)", "start": 22120, "words": 2, "type": "number"},
                {"header": "VEC/DXF file name", "start": 22130, "words": 6, "type": "string"},
            ],
        },
        "air_leakage": {
            "trigger": 23001,
            "title": "エア漏れ検査　TS37001VAA\n(Air leakage inspection machine)",
            "file_name": "Air leakage inspection machine.csv",
            "fields": [
                {"header": "DMC cover", "start": 23020, "words": 16, "type": "string"},
                {"header": "DATE", "start": 23012, "words": 2, "type": "number"},
                {"header": "TIME", "start": 23014, "words": 2, "type": "number"},
                {"header": "Serial number\nof inspection equipment", "start": 23150, "words": 6, "type": "string"},
                {"header": "Numerical inspection program", "start": 23158, "words": 1, "type": "number"},
                {"header": "TEST FAIL value (cm3/min)", "start": 23180, "words": 10, "type": "string"},
                {"header": "Air leakage rate (cm3/min)", "start": 23162, "words": 2, "type": "number"},
                {"header": "Result", "start": 23166, "words": 1, "type": "number"},
            ],
        },
        "performance_inspection": {
            "trigger": 24001,
            "title": "性能検査　TS01017VAA \n( Performance inspection machine )",
            "file_name": "Performance inspection machine.csv",
            "fields": [
                {"header": "DMC Cover", "start": 24020, "words": 16, "type": "string"},
                {"header": "DATE", "start": 24012, "words": 2, "type": "number"},
                {"header": "TIME", "start": 24014, "words": 2, "type": "number"},
                {"header": "Serial number\nof inspection equipment", "start": 24200, "words": 10, "type": "string"},
                {"header": "Set the maximum\nCurrent value  (mA)", "start": 24220, "words": 2, "type": "number"},
                {"header": "Set the minimum\nCurrent value (mA)", "start": 24222, "words": 2, "type": "number"},
                {"header": "Set the maximum\nSpeed value  (r/min)", "start": 24224, "words": 2, "type": "number"},
                {"header": "Set the minimum\nSpeed  value (r/min)", "start": 24226, "words": 2, "type": "number"},
                {"header": "Current value CCW\n(mA)", "start": 24230, "words": 2, "type": "number"},
                {"header": "Judgment", "start": 24234, "words": 1, "type": "number"},
                {"header": "Gear E rotation speed CCW  (r/min)", "start": 24240, "words": 2, "type": "number"},
                {"header": "Judgment", "start": 24244, "words": 1, "type": "number"},
                {"header": "Current value CW\n(mA)", "start": 24250, "words": 2, "type": "number"},
                {"header": "Judgment", "start": 24254, "words": 1, "type": "number"},
                {"header": "Gear E rotation speed CW  (r/min)", "start": 24260, "words": 2, "type": "number"},
                {"header": "Judgment", "start": 24264, "words": 1, "type": "number"},
                {"header": " Program name", "start": 24270, "words": 4, "type": "string"},
            ],
        },
        "terminal_solder_rework": {
            "trigger": None,
            "title": "端子半田リワーク Y013037MAA\n(Terminal solder rework process)",
            "file_name": "Terminal solder rework process.csv",
            "fields": [
                {"header": "QR code on the circuit board", "start": None, "words": 16, "type": "string"},
                {"header": "DATE", "start": None, "words": 2, "type": "number"},
                {"header": "TIME", "start": None, "words": 2, "type": "number"},
            ],
        },
        "jet_solder_rework": {
            "trigger": None,
            "title": "噴流半田リワーク Y013037MAA\n(Jet solder rework process)",
            "file_name": "Jet solder rework process.csv",
            "fields": [
                {"header": "QR code on the circuit board", "start": None, "words": 16, "type": "string"},
                {"header": "DATE", "start": None, "words": 2, "type": "number"},
                {"header": "TIME", "start": None, "words": 2, "type": "number"},
            ],
        },
    },
}
